name: 'Install yq'
description: 'Install yq YAML processor'
runs:
  using: 'composite'
  steps:
    - name: Install yq
      shell: bash
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
