name: 'Release Please: Enable Auto-merge (reusable)'

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number
      merge_method:
        required: false
        type: string
        default: squash

jobs:
  enable:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ inputs.pr_number }}
          merge-method: ${{ inputs.merge_method }}
